import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/availability_block_model.dart';

final supabaseClientProvider = Provider<SupabaseClient>((ref) => Supabase.instance.client);

final calendarRepositoryProvider = Provider<CalendarRepository>((ref) {
  return CalendarRepository(ref.read(supabaseClientProvider));
});

class SelectedDateNotifier extends Notifier<DateTime> {
  @override
  DateTime build() => DateTime.now();
  void setDate(DateTime date) => state = date;
}

final selectedDateProvider = NotifierProvider<SelectedDateNotifier, DateTime>(SelectedDateNotifier.new);

// Fetch current user blocks for chosen date
final dailyBlocksProvider = FutureProvider.family<List<AvailabilityBlockModel>, DateTime>((ref, date) async {
  final repository = ref.watch(calendarRepositoryProvider);
  return repository.getBlocksForDate(date);
});

class CalendarRepository {
  final SupabaseClient _supabase;

  CalendarRepository(this._supabase);

  // Fetch blocks intersecting exactly with the selected Start/End of Day
  Future<List<AvailabilityBlockModel>> getBlocksForDate(DateTime date) async {
    final userId = _supabase.auth.currentUser?.id;
    if (userId == null) return [];

    // Limit boundries of day
    final startOfDay = DateTime(date.year, date.month, date.day).toUtc().toIso8601String();
    final endOfDay = DateTime(date.year, date.month, date.day, 23, 59, 59).toUtc().toIso8601String();

    final response = await _supabase
        .from('availability_blocks')
        .select()
        .eq('tasker_id', userId)
        // Ensure block falls in today's limit
        .gte('start_time', startOfDay)
        .lte('start_time', endOfDay)
        .order('start_time', ascending: true);

    return (response as List<dynamic>)
        .map((e) => AvailabilityBlockModel.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  // Add new block
  Future<void> createBlock({
    required String title,
    required String blockType,
    required DateTime startTime,
    required DateTime endTime,
    bool isRecurring = false,
  }) async {
    final userId = _supabase.auth.currentUser?.id;
    if (userId == null) throw Exception('No autenticado');

    await _supabase.from('availability_blocks').insert({
      'tasker_id': userId,
      'title': title,
      'block_type': blockType,
      'start_time': startTime.toUtc().toIso8601String(),
      'end_time': endTime.toUtc().toIso8601String(),
      'is_recurring': isRecurring,
      // optional id gets generated by uuid
    });
  }
}
